<?php

// CSS Styles declaration
function theme_enqueue_styles() {
    // Load theme personalized css
    wp_enqueue_style('theme-style', get_stylesheet_directory_uri() . '/assets/css/theme.css', array(), filemtime(get_stylesheet_directory() . '/css/theme.css'));
}
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );

function register_menus() {
    
    register_nav_menus(
        array(
            'header-menu' => esc_html__( 'header', 'on header location' ),
            'footer-menu'  => esc_html__( 'footer', 'on footer location' ),
        )
    );
}
add_action( 'after_setup_theme', 'register_menus' );

// Java scripts declaration
function theme_enqueue_scripts() {
		// burger menu
		wp_enqueue_script( 'burger-menu-script', get_stylesheet_directory_uri() . '/assets/js/burger-menu.js', array(), '1.0', true );
        // contact modal
       	wp_enqueue_script( 'contact-modal-script', get_stylesheet_directory_uri() . '/assets/js/contact-modal.js', array(), '1.0', true );
        // single custom type page
		wp_enqueue_script( 'single-cpt-script', get_stylesheet_directory_uri() . '/assets/js/single-fiche-photo.js', array('jquery'), '1.0', true );
		// gallery filters
		wp_enqueue_script( 'gallery-filters', get_stylesheet_directory_uri() . '/assets/js/gallery-filters.js', array('jquery'), '1.0', true );
		wp_localize_script('gallery-filters', 'gallery_filters_JS', array('ajax_url' => admin_url('admin-ajax.php')));
		// gallery load more
		wp_enqueue_script( 'gallery-load-more-script', get_stylesheet_directory_uri() . '/assets/js/gallery-load-more.js', array('jquery','gallery-filters'), '1.0', true );
		wp_localize_script('gallery-load-more-script', 'gallery_load_more_JS', array('ajax_url' => admin_url('admin-ajax.php')));

}
add_action( 'wp_enqueue_scripts', 'theme_enqueue_scripts' );


// suppression of HTML "p" tag generated by plugin contact form7
add_filter('wpcf7_autop_or_not', '__return_false');



// Function to load more photos on gallery
function load_more_photos_from_CPT() {
	$page = $_POST['page'];
	$post_nb = $_POST['post_nb'];
  

	$category_slug = 'mariage';
	$date_order = 'ASC';

	$more_args = array(
		'post_type'      => 'fiche_photo',
		'posts_per_page' => $post_nb,
		'orderby'   => 'date',
		'order'   => $date_order,
		'tax_query' => [
			[
				'taxonomy' => 'categorie',
				'field' => 'slug',
				'terms' => $category_slug,
			],
		], // taxonomies */
		'paged' => $page,
	);
  
	$more_query = new WP_Query($more_args);
  
	if ($more_query->have_posts()) {
		while ($more_query->have_posts()) : $more_query->the_post();
			
			get_template_part('/template-parts/photo-block'); // one photo block build

		endwhile;
		wp_reset_postdata(); // close current loop
	} else {
		echo 'Pas de photos supplémentaires';
	}
  
	wp_die(); // Close correctly Ajax request
  }
  
  add_action('wp_ajax_load_more_photos', 'load_more_photos_from_CPT');
  add_action('wp_ajax_nopriv_load_more_photos', 'load_more_photos_from_CPT');


  
// Function to load photos on gallery according to filters
function load_photos_with_filters()
{
	// get parameters and filters result
	$page = $_POST['page'];
	$post_nb = $_POST['post_nb'];

	$categorie = $_POST['category'];
	$format = $_POST['format'];
	$sort_order = $_POST['order'];


	// build request parameters
	$gallery_args = array(
		'post_type'      => 'fiche_photo',
		'posts_per_page' => $post_nb,
		'paged' => $page,
	);


  	// if results from both filters categorie and format
  	if ($categorie && $format) {
    	$gallery_args += array(
			'tax_query' => [
				'relation' => 'AND',
				[
					'taxonomy' => 'categorie',
					'field' => 'slug',
					'terms' => $categorie,
				],
				[
					'taxonomy' => 'format',
					'field' => 'slug',
					'terms' => $format,
				],
			], // 2 taxonomies */

		);
  	}
	// if results from only filter categorie
  	elseif ($categorie) {
		$gallery_args += array(
			'tax_query' => [
				[
					'taxonomy' => 'categorie',
					'field' => 'slug',
					'terms' => $categorie,
				],
			],

		);
  	}
	// if results from only filter format
	elseif ($format) {
		$gallery_args += array(
			'tax_query' => [
				[
					'taxonomy' => 'format',
					'field' => 'slug',
					'terms' => $format,
				],
			],

		);
  	}

	// results from date filter
	if ($sort_order) {
		$gallery_args += array(
			'order' => $sort_order,
			'orderby' => 'date',
			);
  	}	

/*	  var_dump($gallery_args);*/

	// request to wordpress
	$gallery_query = new WP_Query($gallery_args);
  
	if ($gallery_query->have_posts()) {
		while ($gallery_query->have_posts()) : $gallery_query->the_post();
			
			get_template_part('/template-parts/photo-block'); // one photo block build

		endwhile;
		wp_reset_postdata(); // close current loop
	} else {
		echo 'Pas de photos supplémentaires';
	}
  
	wp_die(); // Close correctly Ajax request
}

add_action('wp_ajax_load_photos', 'load_photos_with_filters');
add_action('wp_ajax_nopriv_load_photos', 'load_photos_with_filters');