<?php

// CSS Styles declaration
function theme_enqueue_styles() {
    // Load theme personalized css
    wp_enqueue_style('theme-style', get_stylesheet_directory_uri() . '/assets/css/theme.css', array(), filemtime(get_stylesheet_directory() . '/css/theme.css'));
}
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );

function register_menus() {
    
    register_nav_menus(
        array(
            'header-menu' => esc_html__( 'header', 'on header location' ),
            'footer-menu'  => esc_html__( 'footer', 'on footer location' ),
        )
    );
}
add_action( 'after_setup_theme', 'register_menus' );

// Java scripts declaration
function theme_enqueue_scripts() {
        // contact modal
       wp_enqueue_script( 'contact-modal-script', get_stylesheet_directory_uri() . '/assets/js/contact-modal.js', array(), '1.0', true );
 
   }
   add_action( 'wp_enqueue_scripts', 'theme_enqueue_scripts' );

// suppression of HTML "p" tag generated by plugin contact form7
add_filter('wpcf7_autop_or_not', '__return_false');